### ISSUE TITLE
No plugins seen by Ableton 11 on M1 Mac on Ventura 13.2

### ISSUE THREAD

**Issue by theuriah** [RomanKubiak/ctrlr#550]
I've tried a couple different versions, including the latest at this point. Tried all the permission changes/removing attributes. They never show up as usable plugins.

**Comment by theuriah** [comment]
Kinda looking like this project is dead.
Real shame...cause it was amazing.

**Comment by theuriah** [comment]
UPDATE:
I was actually able to get the specific versions here running!...in case anyone else needs the link and ends up here:
https://github.com/RomanKubiak/ctrlr/discussions/521#discussioncomment-5273247

**Comment by dobo365** [comment]
This is an issue that some of my users are experiencing.
I'm producing panels with the old 5.3.198 but at this stage I have not been able to identify what the issue is for some plugins to not show up.
Have you been using the AU version or VST version of the plugin?

About the Ctrlr project, it is not dead. I'm using the old versions 5.3.201/198 and I can do very complex stuff with it.
Still waiting seeing someone using all the possibilities.
So, it is a matter of taking the time to learn, to develop and to use it.

**Comment by theuriah** [comment]
Hi! I tried using AU, VST, and VST3 with the other version and I couldn't get any to work. It does seem like I found a version that will work.
I'm VERY glad the project isn't dead, develoment-wise. I really unlocks my hardware synths in a context that makes them very easy to integrate with my DAW, and it's kinda crucial to what I do now.
