### ISSUE TITLE
VST3 and VST2 export not recognized by Cubase (CtrlrX 5.6.30) - Needs another Ctrlr version compiled for each plugin

### ISSUE THREAD

**Issue by dervur** [RomanKubiak/ctrlr#653]
Hello there,

I am trying to export a vst3 in version CtrlrX 5.6.30 within Cubase Elements 12 on Windows 11 version 22H2.
When I export the .exe it is fine and it works fine (didn't try to connect it MIDI but at least it opens). 
Meanwhile, when I export as restricted instance while using CtrlrX vst3 I can see that a file is exported (in the correct folder). Nevertheless, when I scan for VST plugins or close and reopen Cubase the VST is not scanned at all. It is like it is not exported correctly or not identified as a vst3 maybe, I don't know.

I have just been learning CtrlrX for about 2 days, and I'm only now understanding the export options. Do I need to click something to make it work and export correctly to VST3? Or do I have to modify that exported VST3 file somehow to make it work?

If you need any extra information let me know. 
Cheers!

EDIT: I also tried the VST2 version and it works. So it seems to be a VST3 issue only.

**Comment by dervur** [comment]
Ok I think I found out the problem... It seems that the exported version is read by Cubase and other DAWs as an iteration of CtrlrX, so if there is an instance of CtrlrX that has been read before the one that I exported is ignored... Does anybody have any idea of why this happens?

**Comment by damiensellier** [comment]
Currently VST3 instances of CTRLR panels are not working properly because CTRLR is not able to generate different VST3 compliant plugin identifiers. Unfortunately, exported VST3 instances of your panel will always be named after CTRLR | Instigator. The only way to get the correct identifiers for a panel project is to force them at the core during the building step of the VST3 in Xcode/VS/IDE. To export properly identified VST3 plugins it is then required to build a different stock CTRLR VST3 plugin with JUCE Projucer and Xcode/VS/IDE. However, this alternative version of CTRLR VST3 will have the desired panel/plugin identifiers predefined in the Projucer settings. (Plugin Name, Manufacturer Name, Plugin ID, Manufacturer ID etc). This intermediate VST3 plugin will then be able to export a final VST3 version of the panel with the proper identifiers.

Please check : https://github.com/RomanKubiak/ctrlr/discussions/394

FIX: export as VST2 or create your own custom VST3 CtrlrX instance with the appropriate identification properties

**Comment by dervur** [comment]
Hi Damien, thank you very much! Yeah I read about that earlier today... I was having issues compiling though (around 2000 errors), I will take a look at that another day, I'm just tired after the all day trying lol
I also noticed another issue, with VST2, basically I am able to generate only one plugin instance, if I export another one with different name, device, id and so on it seems to be read still as the same plugin (basically I can only do 1 VST and that's it), is this a known issue? Is this solvable in the same way compiling my own VST2 instance in Visual Studio?

**Comment by damiensellier** [comment]
Yes exactly, VST3 will always have the same same name for different exported panels. This is a JUCE library issue. I'm trying to find a way to circumvent that issue for months. If you use a VST2 instance to export your panels that should be OK, exported VST2 should get the right name and be recognised in Cubase as a different plugin. I never tried but from the way the code works it should be ok.


All CtrlrX versions are here : 

CtrlrX v5.6.30.1 macOS Intel
[CtrlrX-5.6.30.1-APP-macOS-Intel.zip](https://github.com/RomanKubiak/ctrlr/files/14659063/CtrlrX-5.6.30.1-APP-macOS-Intel.zip)
[CtrlrX-5.6.30.1-VST3-macOS-Intel.zip](https://github.com/RomanKubiak/ctrlr/files/14659065/CtrlrX-5.6.30.1-VST3-macOS-Intel.zip)
[CtrlrX-5.6.30.1-AU-macOS-Intel.zip](https://github.com/RomanKubiak/ctrlr/files/14659062/CtrlrX-5.6.30.1-AU-macOS-Intel.zip)

CtrlrX v5.6.30.2 macOS Silicon
[CtrlrX v5.6.30.2-APP-MacOS-Silicon.zip](https://github.com/RomanKubiak/ctrlr/files/14803132/CtrlrX.v5.6.30.2-APP-MacOS-Silicon.zip)
[CtrlrX v5.6.30.2-AU-MacOS-Silicon.zip](https://github.com/RomanKubiak/ctrlr/files/14803124/CtrlrX.v5.6.30.2-AU-MacOS-Silicon.zip)
[CtrlrX v5.6.30.2-VST3-MacOS-Silicon.zip](https://github.com/RomanKubiak/ctrlr/files/14803126/CtrlrX.v5.6.30.2-VST3-MacOS-Silicon.zip)

CtrlrX v5.6.30.1 Windows Intel
[CtrlrX 5.6.30.1- EXE-Windows-x64.zip](https://github.com/RomanKubiak/ctrlr/files/14651826/CtrlrX.5.6.30.1-.EXE-Windows-x64.zip)
[CtrlrX-5.6.30.1-VST3-Windows-x64.zip](https://github.com/RomanKubiak/ctrlr/files/14651830/CtrlrX-5.6.30.1-VST3-Windows-x64.zip)
[CtrlrX-5.6.30.1-VST-Windows-x64.zip](https://github.com/RomanKubiak/ctrlr/files/14651832/CtrlrX-5.6.30.1-VST-Windows-x64.zip)

EDIT: The above builds are not working properly and need to be updated because source files were not the right one.

**CtrlrX 5.6.29 Windows 10**
[CtrlrX-x64-5.6.29.zip](https://github.com/RomanKubiak/ctrlr/files/14216062/CtrlrX-x64-5.6.29.zip)
[CtrlrX-x64.vst3-5.6.29.zip](https://github.com/RomanKubiak/ctrlr/files/14216131/CtrlrX-x64.vst3-5.6.29.zip)

**Comment by dervur** [comment]
Hi Damien, 

I noticed it didn't today, I began working on a new instrument and Cubase was not reading it until I took away the one from the other instrument I was working on... Maybe I can fix this by building VST2 as well.

I have those files, as per issue #658 they do not work anymore for some reason, I worked the all day on making it work again, but since I want to be able to build it I will try to fix the building, I think the issue might be that I'm using VS2022 instead of VS2019 and/or maybe something is not installed correctly.

**Comment by damiensellier** [comment]
**29 JUNE 2024**
EDIT: The above CtrlrX v5.6.30.1 builds are not working properly and need to be updated because source files were not the right one.

**CtrlrX 5.6.29 Windows 10**
[CtrlrX-x64-5.6.29.zip](https://github.com/RomanKubiak/ctrlr/files/14216062/CtrlrX-x64-5.6.29.zip)
[CtrlrX-x64.vst3-5.6.29.zip](https://github.com/RomanKubiak/ctrlr/files/14216131/CtrlrX-x64.vst3-5.6.29.zip)

**Comment by dervur** [comment]
Hi Damien, I don't know why these .exe you submitted do not open anymore... I don't know what happened to be honest, I'll keep trying to build it, maybe I will have more success then...

**Comment by dervur** [comment]
Just wanted to specify here that for some reason in this version VST2 works exactly as VST3, I had to compile a proper Ctrlr VST2 version with identifiers for exporting a VST2 correctly.

**Comment by damiensellier** [comment]
I exported a vst2 instance last week to help someone on the discussion board from ctrlrx and the exported instance was recognized in cubase. I just needed to  close and restart cubase to see it in the list.

**Comment by damiensellier** [comment]
So nope, VST2 exported instances are working. Identification process of vst2 is different from DAWs. Cubase on mac just go with the name of the vst file.

**Comment by dervur** [comment]
Hi Damien, 

Try to export two instances of two different panels from the same CtrlrX.dll, for me only the first one I exported works, the second one does not open. It seems like they have the same identifier albeit different names. I don't know if its a similar name thing because I have an export for Volca Sample and Volca Kick (so they both contain Volca as the first word), but the identifier code for VST within the panel is different for both. The only parameters that are equal is the panel author and vendor that made the device, device which this panel controls, name and unique panel ID are all different.
Basically to make the second one I exported I would have to take away from the folder the first one... It's like they couldn't coexist.
This is for Volca Kick
![image](https://github.com/RomanKubiak/ctrlr/assets/77355362/f5db657d-bddc-4e94-8224-1dad4a59f94f)
![image](https://github.com/RomanKubiak/ctrlr/assets/77355362/e13a4b89-12e4-4bcf-979f-f8f6b5c8fafa)
![image](https://github.com/RomanKubiak/ctrlr/assets/77355362/efacbb2c-d28f-4e3c-93c8-ed68483fc7a1)
And this for volca Sample
![image](https://github.com/RomanKubiak/ctrlr/assets/77355362/336f3b1c-5f80-48e4-92f7-2b2dc36aa7a1)
![image](https://github.com/RomanKubiak/ctrlr/assets/77355362/f3eff276-3a78-48b0-b59a-f47b0eaa6976)
![image](https://github.com/RomanKubiak/ctrlr/assets/77355362/94b85f24-e3fe-462a-a6f0-1ec810a38e0f)

To solve I had to do the same thing for the VST3... I don't know if i am the only one with this issue though

**Comment by damiensellier** [comment]
VST3 won't work for sure, but vst2 is supposed to be ok. Maybe Cubase only get the first part of the file name and see them as duplicate. Maybe you should try renaming them with totally different filenames to try. As I remember the way Cubase identifies VST2 is different from mac and PC. 
mac only gets the filename, on PC it passes the id like this  : Panel Name | author 
So it's very possible it won't work, I hardly use PC.

The only way I got everything fine and running was via VST3 by building intermediates with the proper IDs as described previously.

Try if you can renaming the files or going with a panel name like volcakick and volcasampler to see if you have something good and let me know ;)
Good luck

PS: New license with steinberg sdk is for VST3 only anyway

**Comment by dervur** [comment]
Idk, the issue might be Cubase or Windows then, or the name. Albeit, with same name but exported from two separate instances Cubase reads them as two different plugins... Anyway, I will keep exporting from two separate Ctrlr instances as for VST3
